spring.application.name=api

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.datasource.url=jdbc:h2:mem:testdb
api.vacinas.url=https://apidadosabertos.saude.gov.br/vacinacao/doses-aplicadas-pni-2026
